
name: Update README year GIF

on:
  schedule:
    - cron: "30 9 14 8 *" # Tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run update script
        run: python update_gif.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Mise à jour de l'image year.gif"
          git push
